name: healife
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_text_kit: ^4.2.2
  animated_toggle_switch: ^0.8.2
  auto_route: ^8.0.0
  blur: ^3.1.0
  cached_network_image: ^3.2.3
  calendar_view: ^1.1.0
  cloud_firestore: ^4.9.0
  cloud_functions: ^4.4.0
  crop_your_image: ^0.7.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  easy_localization: ^3.0.2
  easy_rich_text: ^2.0.0
  encrypt: ^5.0.1
  equatable: ^2.0.5
  expandable_text: ^2.3.0
  firebase_analytics: ^10.4.5
  firebase_app_check: ^0.2.1+19
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_in_app_messaging: ^0.7.3+5
  firebase_remote_config: ^4.3.3
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.1
  flutter_background_service_ios: ^5.0.0
  flutter_facebook_auth: ^6.0.3
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^16.0.0+1
  flutter_phoenix: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^1.2.0
  image_picker: ^1.0.2
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  like_button: ^2.0.5
  lottie: ^3.0.0
  mask_text_input_formatter: ^2.5.0
  mime: ^1.0.4
  modal_bottom_sheet: ^3.0.0-pre
  onesignal_flutter: ^5.0.4
  path_provider: ^2.1.0
  photo_manager: ^3.0.0-dev.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  skeletonizer: ^1.1.1
  smooth_page_indicator: ^1.1.0
  solid_bottom_sheet: ^0.1.10
  timeago: ^3.5.0
  twitter_login: ^4.4.2
  url_launcher: ^6.1.12
  video_player: ^2.7.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
